[package]
name = "p-hash-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
clap = { version = "4.5.41", features = ["derive"] }
hex = "0.4.3"
image = "0.24.9"
rustdct = "0.7.1"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.9.2"
